### ISSUE TITLE
Mismatch between registry git url and verify_registry_hash usage

### ISSUE THREAD

**Issue by gseastream** [JuliaPackaging/PkgServer.jl#113]
The `verify_registry_hash` method is used to check if registry hashes exist at the git repo as a safeguard, but from what I can tell this checking is not currently happening when using the default settings.

This line in PkgServer.jl sets the default upstream url for the General registry, without a `.git` on the end of it (a string that's repeated in a few other places in the code):

https://github.com/JuliaPackaging/PkgServer.jl/blob/d971ec3af60f8bd4e9a4d2cbcecd465f17ef1b75/src/PkgServer.jl#L44

The `verify_registry_hash` method relies on `Pkg.Operations.get_archive_url_for_version`, which uses `.git` in its regex:

```julia
function get_archive_url_for_version(url::String, ref)
    if (m = match(r"https://github.com/(.*?)/(.*?).git", url)) !== nothing
        return "https://api.github.com/repos/$(m.captures[1])/$(m.captures[2])/tarball/$(ref)"
    end
    return nothing
end
```

I've tried running the methods with the default string and a valid hash, and confirmed that `get_archive_url_for_version` is just returning nothing, and then `verify_registry_hash` doesn't complain because it returns true if nothing was returned:

https://github.com/JuliaPackaging/PkgServer.jl/blob/d971ec3af60f8bd4e9a4d2cbcecd465f17ef1b75/src/resource.jl#L124

So it looks like the check was never actually happening with the default upstream url. Unless this was deliberate, this should be an easy fix.

**Comment by staticfloat** [comment]
Great catch Grant!  Thank you as always for your attention to detail!

X-ref: https://github.com/JuliaPackaging/PkgServer.jl/pull/117
