### ISSUE TITLE
Allow `.tar.gz` at the end of URLs

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/PkgServer.jl#23]
If I want a URL for the tarball of a package at a specific version, all I have to do is look up UUID for the package and look up the `git-tree-sha1` for the version, and then the following URL gives a `.tar.gz` file for the tarball:
```
https://pkg.julialang.org/package/uuid/git-tree-sha1
```

However, this URL will give a 404 error:
```
https://pkg.julialang.org/package/uuid/git-tree-sha1.tar.gz
```

Would it be possible for the Pkg Server to allow the latter form of URL?

**Comment by StefanKarpinski** [comment]
Why? In general, we don't want to bake assumptions about the format into the URL schema. In the future, we may have the client request `/package/$uuid/$hash` and include a `Accept-Encoding` header and negotiate an encoding that the client can receive and that the server can provide. This will allow us to change compression schemes over time if we decide we need to. If we bake the format into the URL schema then we can't do this kind of encoding negotiation as easily.

**Comment by StefanKarpinski** [comment]
If you want to be able to download a URL in a browser and get some file name, then perhaps the [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header would be better since it can set the full file name to something friendly.

**Comment by DilumAluthge** [comment]
Ah that's my mistake. I assumed that if we once served a `.tar.gz` file for a resource, then we guarantee that we will always serve that file.

Presumably we guarantee that we will always serve that *content*, but we make no guarantees about compression algorithm.

**Comment by DilumAluthge** [comment]
> If you want to be able to download a URL in a browser and get some file name, then perhaps the [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header would be better since it can set the full file name to something friendly.

That does sound like it would be the solution. Unfortunately, in this particular use case, the user needs to input a single URL into a form that is submitted for review by an administrator. They are allowed to input one URL for the software, and that is all. And because the setting here is a national laboratory, and the URL is for a tarball that the user wants added to a classified computer system, I don't think there's any way to get them to modify their form so that it accepts both a URL and a Content-Disposition header.
