### ISSUE TITLE
[StorageServer] save artifacts generated during build stage

### ISSUE THREAD

**Issue by johnnychen94** [JuliaPackaging/PkgServer.jl#33]
An example: `curl https://pkg.julialang.org/artifact/cb84c2e2544f3517847d90c13cc11ab911fdbc5c` gets a 404. This artifact doesn't have `download` info, it is built [when requested](https://github.com/JuliaImages/TestImages.jl/blob/eaa94348df619c65956e8cfb0032ecddb7a29d3a/src/TestImages.jl#L101-L116) using the demo from https://julialang.org/blog/2019/11/artifacts/#working_with_artifacts

The current `gen_static.jl` could actually create tarballs for them, as long as they're available in `$JULIA_DEPOT_PATH/artifacts/`. IIUC adding a `Pkg.build(pkg)` could cover some of the similar cases.

**Comment by StefanKarpinski** [comment]
I don't think running arbitrary code on the server is desirable.

**Comment by johnnychen94** [comment]
True, I just opened this issue to check if this is an oversight.
