### ISSUE TITLE
Response contents does not match Content-Encoding

### ISSUE THREAD

**Issue by racinmat** [JuliaPackaging/PkgServer.jl#41]
curl -vvv https://eu.pkg.julialang.org/registries
returns `Content-Encoding: gzip` header, but the response contents is `/registry/23338594-aafe-5451-b93e-139f81909106/911a396527a56e9c8351bdb6d1c02c14b3873d4d`
so clearly, it's not gzipped, but plaintext.

**Comment by StefanKarpinski** [comment]
Ah, good catch—that page is the odd one out.
