### ISSUE TITLE
Suggestion: maintain a list of registry package versions and only update those changed when refreshing registry

### ISSUE THREAD

**Issue by xq114** [JuliaPackaging/PkgServer.jl#64]
When I type `]update` to update my packages, it takes a long time to refresh the entire registry(a long time on removing, and even more on downloading). I observed that many small files of package info are downloaded sequentially which can result in a bad performance. Actually those files stay unchanged.

The situation can be mitigated if only there is a list of registry package containing information of all package versions. While updating packages, we download this list file and find those package info which is out of date. In the best case, it changes nothing and all costs involve a single file download, while now it has to take several minutes to refresh the entire registry.

**Comment by fredrikekre** [comment]
> a long time on removing

Why does that take a long time?

> even more on downloading

Do you have a _extremely_ slow internet connection? The registry is not even 2MB.

> I observed that many small files of package info are downloaded sequentially which can result in a bad performance.

This is not true, Pkg only downloads tarballs, e.g. one single file.

> The situation can be mitigated if only there is a list of registry package containing information of all package versions.

But that is exactly what the registry is?

**Comment by johnnychen94** [comment]
Not quite understand what you're describing, I believe you're suggesting Pkg to only download partial data? There're plans to support partial artifacts https://github.com/JuliaLang/Pkg.jl/issues/1873, and diffs https://github.com/JuliaLang/Pkg.jl/issues/1377 (see the "diffs" section in the protocol RFC).

FWIW, if you currently reside in mainland China, you can use the [BFSU mirror](https://mirrors.bfsu.edu.cn/help/julia/) maintained by TUNA.

**Comment by xq114** [comment]
> Not quite understand what you want, I believe you're suggesting Pkg to only download partial data? There're plans to support partial artifacts [JuliaLang/Pkg.jl#1873](https://github.com/JuliaLang/Pkg.jl/issues/1873), and diffs [JuliaLang/Pkg.jl#1377](https://github.com/JuliaLang/Pkg.jl/issues/1377) (see the "diffs" section in the protocol RFC).
> 
> FWIW, if you currently reside in mainland China, you can use the [BFSU mirror](https://mirrors.bfsu.edu.cn/help/julia/) maintained by TUNA.

Thanks! I'm using BFSU mirror, and I realized the bad performance stems mainly from my hard drive I/O. The time cost on deleting files in folder "General" and extracting the tarball contribute significant portions, not network connection.

Here is the time cost using the mirror:

![image](https://user-images.githubusercontent.com/42310255/87853536-803eaa80-c93d-11ea-9ed9-4498fb83f602.png)
