### ISSUE TITLE
Navigating to us-east.storage.julialang.org in a web browser gives a "403 forbidden" error

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/PkgServer.jl#65]
Navigating to https://kr.storage.julialang.org/ in a web browser gives the following nice message:
> You have reached a [Julia](https://julialang.org/) storage server. It is not meant for browsing but for serving resource required by Julia clients to install packages. To discover and explore the Julia package ecosystem, see [this page](https://julialang.org/packages/) for a list of services.

However, navigating to https://us-east.storage.julialang.org/ in a web browser gives a "403 forbidden" error.

Presumably, navigating to any of the storage servers in a web browser should give the same helpful message.

cc: @staticfloat

**Comment by staticfloat** [comment]
Yep, this is because `us-east` is still running static storage server implementation.  It'll get upgraded in the next few days, as the new storage server implementation has no known bugs anymore, so we're just waiting a bit before rolling it out.

**Comment by DilumAluthge** [comment]
Resolved now.
