### ISSUE TITLE
Reducing latency on cache miss

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/PkgServer.jl#75]
The cache miss latency can be pretty bad, especially for large artifacts.  In the case of the infamous `4747fe73a29e16337cb33702edae26b4e681ae52` artifact, this miss latency can be measured in minutes, which naturally times `nginx` out and results in a 504.  I can think of a few different ways we can improve this:

One way we could reduce this is to forward users who request resources that we don't have, and that are taking more than `N` seconds to fetch, on to the storage server.  E.g. return a 302 to go ask the storage server for the resource directly, while the Pkg server continues to fetch it in the background.

Another way we could reduce this is to immediately start streaming the response to the client, before we even finish verifying the treehash or anything.  This is equivalent in terms of implicitly trusting the storage server, and has the added advantage of having the Pkg server be the one communicating with the user, which is most likely a lower-latency connection than straight to the storage server.

A final way we could reduce this is to immediately serve a 404 if the file is missing, which would cause the Pkg client to immediately fall back to asking GitHub/the original hosting provider, while the Pkg server fetches it in the background.

I consider all three of these responses valid options, it really just depends philosophically on what we want to do.

**Comment by johnnychen94** [comment]
There could be many scenarios that pkg clients are behind a firewall and could not directly communicate with storage servers, or the original Github fallback provider.

I'm not sure if this is already done, probably we could let pkg client send a list of required packages so that pkg servers can pre-fetch resources from the storage server? This could also help to reduce the waiting time when calculating tarball diffs. This won't significantly make the fetching of 1Gb artifact better, though.

**Comment by StefanKarpinski** [comment]
I think streaming would be a viable option as long as the pkg server doesn't save the tarball if it turns out to be bad. After all, the client should (at least post 1.6) be verifying the tarball as well.

**Comment by staticfloat** [comment]
Yeah, the streaming option would stop streaming it to the client as soon as it noticed that it was bad as well, probably triggering an error, which is good as well.

**Comment by staticfloat** [comment]
> There could be many scenarios that pkg clients are behind a firewall and could not directly communicate with storage servers, or the original Github fallback provider.

That's a good point; in that case streaming is by far the best option.

> I'm not sure if this is already done, probably we could let pkg client send a list of required packages so that pkg servers can pre-fetch resources from the storage server? This could also help to reduce the waiting time when calculating tarball diffs. This won't significantly make the fetching of 1Gb artifact better, though.

We had an idea for "package bundles" that was basically this, but so far, this isn't a performance bottleneck for us, so we're probably not going to implement it anytime soon.  If you want to experiment with this, I believe you can simulate this by performing `HEAD` requests for all the resources you want to pre-cache.
