### ISSUE TITLE
Upgrade HTTP.jl version in Manifest.toml

### ISSUE THREAD

**Issue by gseastream** [JuliaPackaging/PkgServer.jl#81]
After a lot of confusion, I discovered that the version of HTTP.jl in the Manifest.toml file (currently 0.8.17) is a version with a known bug in regards to proxies. This bug has been fixed in v0.8.18, as well as the newer version v0.8.19. It might be useful to others to update that in this repo's Manifest file.

**Comment by fredrikekre** [comment]
Do you wanna make a PR? Should just be to clone the repo and run
```
julia --project=. -e 'using Pkg; Pkg.update()
```

**Comment by fredrikekre** [comment]
Perhaps also update the Julia version to 1.5 in the Dockerfile.

**Comment by gseastream** [comment]
Opened a pull request. I've also been successfully using PkgServer behind a corporate proxy for a couple days, but I'm actually still seeing inconsistent hanging when making requests to the storage servers with HTTP.jl. I'm not sure what the cause could be, nor how best to reproduce it since it probably depends on our environment. Would you know if there's anything about PkgServer that might be causing this issue? Or could it still be HTTP.jl?

The problem is that sometimes during http requests it will never actually start the request, and it'll hang forever because the timeout argument doesn't kill the request since it never actually "started". I've only been able to work around this problem because I wrapped all requests in the PkgServer code to spawn the http request in a thread and kill that thread if it's not done after a certain amount of time (and retry a couple times after that). Probably not a great solution but I couldn't think of anything else.

**Comment by staticfloat** [comment]
Thanks Grant, this is helpful!  I'm not certain we're seeing the same issues on the public PkgServers, but it's great to have another user who can pound on things in different ways.  Please do open issues (and ping me) if you find strange failure modes.
